version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3100:3000"
    restart: unless-stopped

  backend:
    build:
      context: ./NewBackend
      dockerfile: Dockerfile
    ports:
      - "5500:5000"
    env_file:
      - ./NewBackend/.env
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # add other env vars if needed

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: wagaz_db
    volumes:
      - wagaz_postgres_data:/var/lib/postgresql/data
    ports:
      - "5543:5432"


volumes:
  wagaz_postgres_data:
