version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped

  backend:
    build:
      context: ./NewBackend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # add other env vars if needed

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: wagazuser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: wagazdb
    volumes:
      - wagaz_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  wagaz_postgres_data:
